In [1]:
# importing the libraries that are important for this project 
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# importing the dataset
df = pd.read_csv(r"C:\Skills\Student Performance Predictor\Dataset\Students_Performance_dataset.csv")

# Understanding the data

In [3]:
# checking the shape of data
df.shape

(1194, 31)

In [14]:
# we can see there are 1194 rows and 31 collumns now we will see how the data looks like 
df.sample(5)

,University Admission year,Gender,Age,H.S.C passing year,Program,Current Semester,Do you have meritorious scholarship ?,Do you use University transportation?,How many hour do you study daily?,How many times do you seat for study in a day?,...,What is you interested area?,What is your relationship status?,Are you engaged with any co-curriculum activities?,With whom you are living with?,Do you have any health issues?,What was your previous SGPA?,Do you have any physical disabilities?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
170,2021,Male,22,2020,BCSE,4,Yes,Yes,4,2,...,Software,Single,Yes,Family,No,2.16,No,2.75,35,40000
301,2022,Female,21,2020,BCSE,2,Yes,Yes,2,1,...,Software,Single,No,Family,No,3.70,No,3.70,12,120000
664,2022,Male,20,2020,BCSE,2,Yes,Yes,2,1,...,Software,Single,No,Family,No,1.75,No,1.75,11,30000
747,2019,Female,25,2018,BCSE,10,No,No,5,3,...,Data Science,Relationship,Yes,Bachelor,No,2.45,No,3.54,116,34000
414,2020,Male,22,2019,BCSE,6,No,Yes,4,3,...,Data Science,Relationship,No,Family,No,3.02,No,3.20,70,20000

In [7]:
# now we can check the datatypes of the features 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1194 entries, 0 to 1193
Data columns (total 31 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   University Admission year                                                  1194 non-null   int64
 1   Gender                                                                     1194 non-null   object
 2   Age                                                                        1194 non-null   int64
 3   H.S.C passing year                                                         1194 non-null   int64
 4   Program                                                                    1194 non-null   object
 5   Current Semester                                                           1194 non-null   int64
 6   Do you have meritorious scholarship ?                                      1194 non-null   object
 7   Do you use University transportation?                                      1194 non-null   object
 8   How many hour do you study daily?                                          1194 non-null   int64
 9   How many times do you seat for study in a day?                             1194 non-null   int64
 10  What is your preferable learning mode?                                     1194 non-null   object
 11  Do you use smart phone?                                                    1194 non-null   object
 12  Do you have personal Computer?                                             1194 non-null   object
 13  How many hour do you spent daily in social media?                          1194 non-null   int64
 14  Status of your English language proficiency                                1194 non-null   object
 15  Average attendance on class                                                1194 non-null   object
 16  Did you ever fall in probation?                                            1194 non-null   object
 17  Did you ever got suspension?                                               1194 non-null   object
 18  Do you attend in teacher consultancy for any kind of academical problems?  1194 non-null   object
 19  What are the skills do you have ?                                          1193 non-null   object
 20  How many hour do you spent daily on your skill development?                1194 non-null   int64
 21  What is you interested area?                                               1194 non-null   object
 22  What is your relationship status?                                          1194 non-null   object
 23  Are you engaged with any co-curriculum activities?                         1194 non-null   object
 24  With whom you are living with?                                             1194 non-null   object
 25  Do you have any health issues?                                             1194 non-null   object
 26  What was your previous SGPA?                                               1194 non-null   float64
 27  Do you have any physical disabilities?                                     1194 non-null   object
 28  What is your current CGPA?                                                 1194 non-null   float64
 29  How many Credit did you have completed?                                    1194 non-null   int64
 30  What is your monthly family income?                                        1194 non-null   int64
dtypes: float64(2), int64(10), object(19)
memory usage: 289.3+ KB

In [8]:
# checking the total amount of nul values
df.isnull().sum()

University Admission year                                                    0
Gender                                                                       0
Age                                                                          0
H.S.C passing year                                                           0
Program                                                                      0
Current Semester                                                             0
Do you have meritorious scholarship ?                                        0
Do you use University transportation?                                        0
How many hour do you study daily?                                            0
How many times do you seat for study in a day?                               0
What is your preferable learning mode?                                       0
Do you use smart phone?                                                      0
Do you have personal Computer?                                               0
How many hour do you spent daily in social media?                            0
Status of your English language proficiency                                  0
Average attendance on class                                                  0
Did you ever fall in probation?                                              0
Did you ever got suspension?                                                 0
Do you attend in teacher consultancy for any kind of academical problems?    0
What are the skills do you have ?                                            1
How many hour do you spent daily on your skill development?                  0
What is you interested area?                                                 0
What is your relationship status?                                            0
Are you engaged with any co-curriculum activities?                           0
With whom you are living with?                                               0
Do you have any health issues?                                               0
What was your previous SGPA?                                                 0
Do you have any physical disabilities?                                       0
What is your current CGPA?                                                   0
How many Credit did you have completed?                                      0
What is your monthly family income?                                          0
dtype: int64

In [9]:
# we can see that there is only one missing value 
# now we will check the numerical features of the dataset 
df.describe()

,University Admission year,Age,H.S.C passing year,Current Semester,How many hour do you study daily?,How many times do you seat for study in a day?,How many hour do you spent daily in social media?,How many hour do you spent daily on your skill development?,What was your previous SGPA?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
count,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1194.000000,1.194000e+03
mean,2020.515075,21.343384,2019.214405,6.539363,3.131491,1.940536,3.289782,2.185092,2.683945,3.165603,71.842546,6.248812e+04
std,1.354954,1.613338,1.380960,3.809884,1.649597,0.856305,2.289547,1.296101,0.871592,0.750132,48.074338,7.617356e+04
min,2013.000000,18.000000,2012.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000e+03
25%,2020.000000,20.000000,2019.000000,3.000000,2.000000,1.000000,2.000000,1.000000,2.200000,2.900000,23.000000,3.000000e+04
50%,2021.000000,21.000000,2020.000000,7.000000,3.000000,2.000000,3.000000,2.000000,2.680000,3.210000,78.000000,5.000000e+04
75%,2022.000000,22.000000,2020.000000,10.000000,4.000000,2.000000,4.000000,3.000000,3.380000,3.670000,117.000000,7.400000e+04
max,2023.000000,27.000000,2028.000000,24.000000,13.000000,7.000000,20.000000,12.000000,4.000000,4.000000,145.000000,2.000000e+06

In [12]:
# now we can check if there are any duplicate values in the data
df.duplicated().sum()
# there are no duplicated values

np.int64(0)

In [13]:
# we can see the correlation between the numerical collumns 
df.corr(numeric_only=True)

,University Admission year,Age,H.S.C passing year,Current Semester,How many hour do you study daily?,How many times do you seat for study in a day?,How many hour do you spent daily in social media?,How many hour do you spent daily on your skill development?,What was your previous SGPA?,What is your current CGPA?,How many Credit did you have completed?,What is your monthly family income?
University Admission year,1.000000,-0.650018,0.782228,-0.834406,-0.009701,-0.011147,-0.023836,-0.134997,-0.085830,-0.113261,-0.672899,-0.047732
Age,-0.650018,1.000000,-0.665891,0.585559,-0.012256,0.018433,0.020693,0.121907,0.020770,0.066030,0.476374,0.028034
H.S.C passing year,0.782228,-0.665891,1.000000,-0.579773,0.003068,-0.003386,0.021160,-0.067149,-0.174903,-0.054161,-0.391187,0.025582
Current Semester,-0.834406,0.585559,-0.579773,1.000000,-0.021964,0.040414,0.065189,0.187879,-0.054151,0.177822,0.903204,0.122780
How many hour do you study daily?,-0.009701,-0.012256,0.003068,-0.021964,1.000000,0.374046,0.016313,0.137195,0.043620,0.023696,-0.006609,-0.000492
How many times do you seat for study in a day?,-0.011147,0.018433,-0.003386,0.040414,0.374046,1.000000,-0.063458,0.126989,0.007952,0.048802,0.061102,0.036434
How many hour do you spent daily in social media?,-0.023836,0.020693,0.021160,0.065189,0.016313,-0.063458,1.000000,-0.034756,-0.178530,-0.052876,0.106239,0.053967
How many hour do you spent daily on your skill development?,-0.134997,0.121907,-0.067149,0.187879,0.137195,0.126989,-0.034756,1.000000,0.003063,0.083225,0.185845,0.011152
What was your previous SGPA?,-0.085830,0.020770,-0.174903,-0.054151,0.043620,0.007952,-0.178530,0.003063,1.000000,0.755062,-0.126091,-0.121871
What is your current CGPA?,-0.113261,0.066030,-0.054161,0.177822,0.023696,0.048802,-0.052876,0.083225,0.755062,1.000000,0.222047,-0.000275
How many Credit did you have completed?,-0.672899,0.476374,-0.391187,0.903204,-0.006609,0.061102,0.106239,0.185845,-0.126091,0.222047,1.000000,0.165812
What is your monthly family income?,-0.047732,0.028034,0.025582,0.122780,-0.000492,0.036434,0.053967,0.011152,-0.121871,-0.000275,0.165812,1.000000

In [15]:
# Now we will perform basic Eda To understand our dataframe

# EDA

In [17]:
df['Program'].value_counts()
# we can see that all the students are from the same program so we can remove the 'Program' column

Program
BCSE    1194
Name: count, dtype: int64

In [23]:
# we removed the collumn which was not required
# df = df.drop('Program',axis=1)
df.shape

(1194, 30)

(1194, 30)